modLoader="javafml"
loaderVersion="[40,)"
license="CC BY-NC-SA 3.0"

[[mods]]
modId="mcmodsplash"
version="3.3"
displayName="MC百科标语"
logoFile="logo.png"
credits="感谢FeO_Fe2O3提出的奇怪想法,还有小乐er以及其他几位贡献者;感谢喵呜机(百科站长)整的生屮标语(没笑停过的那种)"
authors="重生是希望(www.mcmod.cn/author/24402.html)，热血少年小乐(www.mcmod.cn/author/27343.html)，FeO_Fe2O3(www.mcmod.cn/author/27421.html)，初雪·冰(www.mcmod.cn/author/25810.html)，187J3X1(www.mcmod.cn/author/28442.html)，BunnimimiTotem(www.mcmod.cn/author/26478.html)，工具人巴尼(www.mcmod.cn/author/30431.html)"
description='''
公元2024年,已经初二的187J3X1终于学会了Java(不多,但够用),终于整出了在线获得标语的法子..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................(编不下去了)
'''

[[dependencies.mcmodsplash]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mcmodsplash]]
    modId="minecraft"
    mandatory=true
    versionRange="[*,)"
    ordering="NONE"
    side="BOTH"
